# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
width = 800
height = 600


class Control():
    def __init__(self) -> None:
        pass


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(width, height)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 781, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.on_1 = QtWidgets.QPushButton(self.centralwidget)
        self.on_1.setGeometry(QtCore.QRect(270, 190, 75, 23))
        self.on_1.setDefault(False)
        self.on_1.setObjectName("on_1")
        self.off_1 = QtWidgets.QPushButton(self.centralwidget)
        self.off_1.setGeometry(QtCore.QRect(270, 210, 75, 23))
        self.off_1.setObjectName("off_1")
        self.off_3 = QtWidgets.QPushButton(self.centralwidget)
        self.off_3.setGeometry(QtCore.QRect(270, 290, 75, 23))
        self.off_3.setObjectName("off_3")
        self.on_2 = QtWidgets.QPushButton(self.centralwidget)
        self.on_2.setGeometry(QtCore.QRect(390, 190, 75, 23))
        self.on_2.setDefault(False)
        self.on_2.setObjectName("on_2")
        self.off_2 = QtWidgets.QPushButton(self.centralwidget)
        self.off_2.setGeometry(QtCore.QRect(390, 210, 75, 23))
        self.off_2.setObjectName("off_2")
        self.on_3 = QtWidgets.QPushButton(self.centralwidget)
        self.on_3.setGeometry(QtCore.QRect(270, 270, 75, 23))
        self.on_3.setDefault(False)
        self.on_3.setObjectName("on_3")
        self.off_4 = QtWidgets.QPushButton(self.centralwidget)
        self.off_4.setGeometry(QtCore.QRect(390, 290, 75, 23))
        self.off_4.setObjectName("off_4")
        self.on_4 = QtWidgets.QPushButton(self.centralwidget)
        self.on_4.setGeometry(QtCore.QRect(390, 270, 75, 23))
        self.on_4.setDefault(False)
        self.on_4.setObjectName("on_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.on_1.clicked.connect(lambda:  self.log("hello on 1"))
        self.on_2.clicked.connect(lambda:  self.log("hello on 2"))
        self.on_3.clicked.connect(lambda:  self.log("hello on 3"))
        self.on_4.clicked.connect(lambda:  self.log("hello on 4"))

        self.off_1.clicked.connect(lambda:  self.log("hello off 1"))
        self.off_2.clicked.connect(lambda:  self.log("hello off 2"))
        self.off_3.clicked.connect(lambda:  self.log("hello off 3"))
        self.off_4.clicked.connect(lambda:  self.log("hello off 4"))

        self.off_1.setStyleSheet("background-color: yellow;")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "DIEU KHIEN 4 THIET BI"))
        self.on_1.setText(_translate("MainWindow", "ON"))
        self.off_1.setText(_translate("MainWindow", "OFF"))
        self.off_3.setText(_translate("MainWindow", "OFF"))
        self.on_2.setText(_translate("MainWindow", "ON"))
        self.off_2.setText(_translate("MainWindow", "OFF"))
        self.on_3.setText(_translate("MainWindow", "ON"))
        self.off_4.setText(_translate("MainWindow", "OFF"))
        self.on_4.setText(_translate("MainWindow", "ON"))

    def log(self, msg):
        print(msg)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
