# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.pyplot as plt
import numpy as np
import time

# import time

state_lamp_1 = "off"
state_lamp_2 = "off"
state_lamp_3 = "off"

state_mode_1 = False
state_mode_2 = False


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        global state_mode_1, state_mode_2
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name_title = QtWidgets.QLabel(self.centralwidget)
        self.name_title.setGeometry(QtCore.QRect(170, 0, 631, 121))
        self.name_title.setMaximumSize(QtCore.QSize(801, 16777215))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.name_title.setFont(font)
        self.name_title.setAlignment(QtCore.Qt.AlignCenter)
        self.name_title.setObjectName("name_title")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(10, 10, 151, 111))
        self.logo.setText("")
        self.logo.setTextFormat(QtCore.Qt.RichText)
        self.logo.setPixmap(QtGui.QPixmap("static/imgs/logo.jpeg"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setWordWrap(True)
        self.logo.setObjectName("logo")
        self.footer_name = QtWidgets.QLabel(self.centralwidget)
        self.footer_name.setGeometry(QtCore.QRect(40, 490, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.footer_name.setFont(font)
        self.footer_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.footer_name.setAlignment(QtCore.Qt.AlignCenter)
        self.footer_name.setObjectName("footer_name")
        self.footer_mssv = QtWidgets.QLabel(self.centralwidget)
        self.footer_mssv.setGeometry(QtCore.QRect(490, 490, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.footer_mssv.setFont(font)
        self.footer_mssv.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.footer_mssv.setAlignment(QtCore.Qt.AlignCenter)
        self.footer_mssv.setObjectName("footer_mssv")
        self.lamp_1 = QtWidgets.QLabel(self.centralwidget)
        self.lamp_1.setGeometry(QtCore.QRect(30, 160, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.lamp_1.setFont(font)
        self.lamp_1.setText("")
        self.lamp_1.setPixmap(QtGui.QPixmap("static/imgs/lamp_off.png"))
        self.lamp_1.setScaledContents(True)
        self.lamp_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lamp_1.setObjectName("lamp_1")
        self.lamp_2 = QtWidgets.QLabel(self.centralwidget)
        self.lamp_2.setGeometry(QtCore.QRect(130, 160, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.lamp_2.setFont(font)
        self.lamp_2.setText("")
        self.lamp_2.setPixmap(QtGui.QPixmap("static/imgs/may_lanh_off.png"))
        self.lamp_2.setScaledContents(True)
        self.lamp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lamp_2.setObjectName("lamp_2")
        self.lamp_3 = QtWidgets.QLabel(self.centralwidget)
        self.lamp_3.setGeometry(QtCore.QRect(230, 160, 81, 91))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.lamp_3.setFont(font)
        self.lamp_3.setText("")
        self.lamp_3.setPixmap(QtGui.QPixmap("static/imgs/lamp_3_1.png"))
        self.lamp_3.setScaledContents(True)
        self.lamp_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lamp_3.setObjectName("lamp_3")
        self.on_lamp_1 = QtWidgets.QPushButton(self.centralwidget)
        self.on_lamp_1.setGeometry(QtCore.QRect(30, 270, 91, 23))
        self.on_lamp_1.setObjectName("on_lamp_1")
        self.off_lamp_1 = QtWidgets.QPushButton(self.centralwidget)
        self.off_lamp_1.setGeometry(QtCore.QRect(30, 300, 91, 23))
        self.off_lamp_1.setObjectName("off_lamp_1")
        self.on_off_lamp_2 = QtWidgets.QPushButton(self.centralwidget)
        self.on_off_lamp_2.setGeometry(QtCore.QRect(130, 270, 91, 51))
        self.on_off_lamp_2.setObjectName("may_lanh")
        self.slider_lamp_3 = QtWidgets.QSlider(self.centralwidget)
        self.slider_lamp_3.setGeometry(QtCore.QRect(230, 280, 81, 31))
        self.slider_lamp_3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_lamp_3.setObjectName("slider_lamp_3")
        self.mode_1 = QtWidgets.QPushButton(self.centralwidget)
        self.mode_1.setGeometry(QtCore.QRect(70, 350, 91, 41))
        self.mode_1.setObjectName("mode_1")
        self.mode_2 = QtWidgets.QPushButton(self.centralwidget)
        self.mode_2.setGeometry(QtCore.QRect(170, 350, 91, 41))
        self.mode_2.setObjectName("mode_2")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(70, 420, 191, 41))
        self.exit.setObjectName("exit")
        self.chart_widget = QtWidgets.QWidget(self.centralwidget)
        self.chart_widget.setGeometry(QtCore.QRect(400, 120, 380, 340))
        self.chart_layout = QtWidgets.QVBoxLayout(self.chart_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.exit.clicked.connect(self.control_exit)

        self.on_lamp_1.clicked.connect(
            lambda: self.control_lamp("lamp_1", self.lamp_1, "on"))
        self.off_lamp_1.clicked.connect(
            lambda: self.control_lamp("lamp_1", self.lamp_1, "off"))
        self.on_off_lamp_2.clicked.connect(
            lambda: self.control_lamp("lamp_2", self.lamp_2, "inv"))

        self.slider_lamp_3.valueChanged.connect(
            lambda: self.handle_slider(self.lamp_3))

        self.mode_1.clicked.connect(lambda: self.control_mode_1(
            self.lamp_1, self.lamp_2, self.lamp_3))

        self.mode_2.clicked.connect(lambda: self.control_mode_2(
            self.lamp_1, self.lamp_2, self.lamp_3))

        self.fig, self.ax = plt.subplots()
        self.canvas = FigureCanvas(self.fig)
        self.chart_layout.addWidget(self.canvas)

        self.plot_chart()

        # self.widget = MyGraph()
        # MyGraph()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_title.setText(_translate(
            "MainWindow", "DIEU KHIEN 3 THIET BI"))
        self.footer_name.setText(_translate("MainWindow", "VO MINH THUAN"))
        self.footer_mssv.setText(_translate("MainWindow", "MSSV: 21161366"))
        self.on_lamp_1.setText(_translate("MainWindow", "ON LAMP 1"))
        self.off_lamp_1.setText(_translate("MainWindow", "OFF LAMP 2"))
        self.on_off_lamp_2.setText(_translate("MainWindow", "MAY LANH"))
        self.mode_1.setText(_translate("MainWindow", "MODE 1"))
        self.mode_2.setText(_translate("MainWindow", "MODE 2"))
        self.exit.setText(_translate("MainWindow", "EXIT"))

    def control_exit(self):
        import sys
        sys.exit(app)

    def handle_slider(self, name):
        value = self.slider_lamp_3.value()
        level = int(value/20 + 1)
        name.setPixmap(QtGui.QPixmap("static/imgs/lamp_3_"+str(level)+".png"))

    def control_lamp(self, name, nameControl, state):
        global state_lamp_1, state_lamp_2, state_lamp_3
        if state == "on":
            nameControl.setPixmap(
                QtGui.QPixmap("static/imgs/lamp_on.png"))
            if name == "lamp_1":
                state_lamp_1 = "on"
        if state == "off":
            nameControl.setPixmap(
                QtGui.QPixmap("static/imgs/lamp_off.png"))
            if name == "lamp_1":
                state_lamp_1 = "on"
        if state == "inv":
            if state_lamp_2 == "on":
                state_lamp_2 = "off"
                nameControl.setPixmap(
                    QtGui.QPixmap("static/imgs/may_lanh_off.png"))
            else:
                state_lamp_2 = "on"
                nameControl.setPixmap(
                    QtGui.QPixmap("static/imgs/may_lanh_on.png"))

    def control_mode_1(self, lamp_1, lamp_2, lamp_3):
        global state_lamp_1, state_lamp_2, state_lamp_3
        state_lamp_1 = "on"
        state_lamp_2 = "on"
        state_lamp_2 = "on"
        lamp_1.setPixmap(
            QtGui.QPixmap("static/imgs/lamp_on.png"))
        lamp_2.setPixmap(
            QtGui.QPixmap("static/imgs/may_lanh_on.png"))
        lamp_3.setPixmap(QtGui.QPixmap(
            "static/imgs/lamp_3_"+str(2)+".png"))
        self.slider_lamp_3.setValue(20)

    def control_mode_2(self, lamp_1, lamp_2, lamp_3):
        global state_lamp_1, state_lamp_2, state_lamp_3
        state_lamp_1 = "off"
        state_lamp_2 = "off"
        state_lamp_2 = "off"
        lamp_1.setPixmap(
            QtGui.QPixmap("static/imgs/lamp_off.png"))
        lamp_2.setPixmap(
            QtGui.QPixmap("static/imgs/may_lanh_off.png"))
        lamp_3.setPixmap(QtGui.QPixmap(
            "static/imgs/lamp_3_"+str(1)+".png"))
        self.slider_lamp_3.setValue(0)

    def plot_chart(self):
        self.ax.clear()
        rects1 = self.ax.bar(
            [1, 3, 5, 7, 9], [5, 2, 7, 8, 2], label="Example one")
        rects2 = self.ax.bar(
            [2, 4, 6, 8, 10], [8, 6, 2, 5, 6],
            label="Example two", color='y')
        self.ax.bar_label(rects1)
        self.ax.bar_label(rects2)
        # self.ax.set_xlabel('Bar Height', size=8)
        self.ax.set_ylabel('Bar Number', size=10)
        self.ax.set_title('Example 3 - Bar Graph')
        self.ax.legend()
        self.canvas.draw()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
